---
title: "Cleaning Comp Dataset - Jackie McCarty"
author: "Jacqueline McCarty"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
```

```{r}
library(readr)
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)

```

```{r}
counts <- read_tsv("gene dataset/Compliment dataset/GSE152418_raw_counts_GRCh38.p13_NCBI.tsv")
annot <- read_tsv("gene dataset/Compliment dataset/Human.GRCh38.p13.annot.tsv")
series_mat <- readLines("gene dataset/Compliment dataset/GSE152418_series_matrix.txt")


```


```{r}
dim(counts)
dim(annot)
length(series_mat)

colnames(counts)[1:10]
colnames(annot)
head(series_mat, 20)
```
series matrix
```{r}
geo_row <- function(prefix, lines) {
  line <- lines[startsWith(lines, prefix)]
  if (length(line) == 0) stop(paste("Could not find row:", prefix))
  vals <- strsplit(line, "\t")[[1]][-1]
  vals <- gsub('^"|"$', "", vals)
  vals
}

sample_ids <- geo_row("!Sample_geo_accession", series_mat)
sample_titles <- geo_row("!Sample_title", series_mat)

char_lines <- series_mat[startsWith(series_mat, "!Sample_characteristics_ch1")]
char_split <- lapply(char_lines, function(x) {
  vals <- strsplit(x, "\t")[[1]][-1]
  vals <- gsub('^"|"$', "", vals)
  vals
})

extract_char <- function(pattern, char_split, n_samples) {
  row_idx <- grep(pattern, sapply(char_split, `[`, 1), ignore.case = TRUE)
  if (length(row_idx) == 0) return(rep(NA, n_samples))
  vals <- char_split[[row_idx[1]]]
  sub("^[^:]+:\\s*", "", vals)
}

metadata <- data.frame(
  sample_id = sample_ids,
  title = sample_titles,
  days_post_symptom_onset = extract_char("^days_post_symptom_onset:", char_split, length(sample_ids)),
  gender = extract_char("^gender:", char_split, length(sample_ids)),
  disease_state = extract_char("^disease state:", char_split, length(sample_ids)),
  severity = extract_char("^severity:", char_split, length(sample_ids)),
  stringsAsFactors = FALSE
)

metadata$days_post_symptom_onset <- suppressWarnings(as.numeric(metadata$days_post_symptom_onset))

head(metadata)
table(metadata$disease_state, useNA = "ifany")
table(metadata$severity, useNA = "ifany")
```


```{r}
count_sample_cols <- colnames(counts)[-1]

# Keeping only the metadata rows that appear in counts
metadata <- metadata %>%
  filter(sample_id %in% count_sample_cols) %>%
  arrange(match(sample_id, count_sample_cols))

all(metadata$sample_id == count_sample_cols)
```



#merging annotation and counts table
```{r}
counts_annot <- counts %>%
  left_join(annot, by = "GeneID")

head(counts_annot[, 1:6])
```


```{r}
metadata2 <- metadata %>%
  filter(disease_state %in% c("COVID-19", "Healthy")) %>%
  mutate(disease_state = factor(disease_state, levels = c("Healthy", "COVID-19")))

counts2 <- counts_annot %>%
  select(GeneID, all_of(metadata2$sample_id))
```


```{r}
final_clean_RNAComp <- counts2 %>%
  pivot_longer(-GeneID, names_to = "sample_id", values_to = "count") %>%
  left_join(metadata2, by = "sample_id")
```


```{r}
write.csv(metadata2, "metadata2_clean.csv", row.names = FALSE)
write.csv(counts2, "counts2_clean.csv", row.names = FALSE)
write.csv(counts_annot, "counts_with_annotation.csv", row.names = FALSE)
write.csv(final_clean_RNAComp, "final_clean_RNAComp.csv", row.names = FALSE)
```






