---
title: "CLeaning Data RNA - Data 205 - Jacqueline McCarty"
author: "Jacqueline McCarty"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readr)
library(tibble)
library(stringr)
```


```{r}
counts <- read_csv("gene dataset/GSE156063_swab_gene_counts.csv")
meta_file <- readLines("gene dataset/GSE156063_series_matrix.txt")

processed_metadata_file <- "cleaned_metadata.csv"
processed_expression_file <- "log_expression_matrix.csv"
processed_analysis_file <- "final_analysis_dataset.csv"
```

```{r}
#remove \t and quotes
clean_meta <- gsub("\\\\t", " ", meta_file)
clean_meta <- gsub('\\"', '', clean_meta)  
```


```{r}
key <- sub("[ \t].*", "", clean_meta)

value <- sub("^[^ \t]+[ \t]+", "", clean_meta)

meta_data <- data.frame(key, value)
head(meta_data)
```
# Convert Raw Counts to Log Expression Matrix

```{r}
gene_counts2 <- counts %>%
  rename(gene_id = 1)

X <- gene_counts2 %>%
  column_to_rownames("gene_id") %>%
  mutate(across(everything(), as.numeric)) %>%
  as.matrix()

X_t <- t(X)

X_log <- log1p(X_t)

X_log_df <- as.data.frame(X_log) %>%
  rownames_to_column("sample_id")
```

```{r}
lines <- meta_file

stop_line <- which(lines == "!series_matrix_table_begin")
meta_lines <- lines[1:(stop_line - 1)]

sample_lines <- meta_lines[str_starts(meta_lines, "!Sample_")]

sample <- read.delim(
  text = paste(sample_lines, collapse = "\n"),
  sep = "\t",
  header = FALSE,
  quote = "",
  fill = TRUE,
  stringsAsFactors = FALSE,
  check.names = FALSE)

field <- sample[[1]]
sample <- sample[-1]

colnames(sample) <- gsub('"', "", sample[1, ])
sample <- sample[-1, ]

sample <- cbind(field = field[-1], sample)
meta <- sample %>%
  pivot_longer(-field, names_to = "geo_accession", values_to = "value") %>%
  pivot_wider(names_from = field, values_from = value, values_fn = ~ paste(.x, collapse = "; ")
)
```

```{r}
meta2 <- meta %>%
  mutate(
    char1 = `!Sample_characteristics_ch1`,
    sample_id = str_extract(geo_accession, "RR057[a-z]?_\\d+"),
    sars_rpm = str_extract(char1, "sars-cov-2 rpm: (POS|NEG)") %>%
      str_remove("sars-cov-2 rpm: "),
    sars_pcr = str_extract(char1, "sars-cov-2 pcr: [0-9.]+") %>%
      str_remove("sars-cov-2 pcr: ") %>%
      as.numeric(),
    sars_pcr_log10 = log10(sars_pcr + 1)
  )
```


```{r}
innate_genes <- c(
  "ENSG00000185745",  # ISG15
  "ENSG00000115415",  # OAS1
  "ENSG00000171855"   # IFITM3
)

innate_mat <- X[rownames(X) %in% innate_genes, , drop = FALSE]

innate_score <- colMeans(innate_mat, na.rm = TRUE)

innate_df <- tibble(
  sample_id = names(innate_score),
  innate_score = log1p(innate_score)
)

final_data <- innate_df %>%
  left_join(meta2, by = "sample_id")
```


```{r}
write_csv(X_log_df, "log_expression_matrix.csv")
write_csv(meta2, "cleaned_metadata.csv")
write_csv(final_data, "final_analysis_dataset.csv")
```

```{r}
final_data <- innate_df %>%
  left_join(meta2, by = "sample_id")

write_csv(final_data, "final_analysis_dataset.csv")


cat("Cleaning complete.\n")
cat("Saved files:\n")
write_csv(X_log_df, processed_expression_file)
write_csv(meta2, processed_metadata_file)
write_csv(final_data, processed_analysis_file)
```




